spring:
  datasource:
    url: jdbc:mysql://localhost:3306/j133_spring_demo?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update # Tabele zostanÄ… wygenerowane przez springa